### ISSUE TITLE
Seatbelt prompt doesn't update to default keybind

### ISSUE THREAD

**Issue by saddleupandride** [TFNRP/seatbelt#13]
Changed the default keybind to B in config, B puts on and removes the seatbelt, but the prompt still says to press K to put it on
https://media.discordapp.net/attachments/953230547138777098/1132074129693093968/image.png?width=1152&height=81
https://media.discordapp.net/attachments/953230547138777098/1132074143936954510/image.png?width=1033&height=662
(github isn't cooperating with images, apologies for the random links)

**Comment by MrGriefs** [comment]
unfortunately, this is a limitation of this script. the control shown in the help text is ephemeral at best and cannot be used to show the actual binded key at runtime. this is also a limitation of FiveM's custom key registry.

the best solution is to change the text [`INPUT_REPLAY_SHOWHOTKEY`](https://github.com/TFNRP/seatbelt/blob/main/client.lua#L98) to the corresponding default key you've set in config.lua, in this case it would be `INPUT_REPLAY_STARTPOINT` to display the <kbd>B</kbd> key.

you can find the "full" control list here: https://docs.fivem.net/docs/game-references/controls
closing this issue as no support
