### ISSUE TITLE
Upon initiating the plugin, I encountered the following error.

### ISSUE THREAD

**Issue by MancyMiao** [TFNRP/seatbelt#14]
[         script:yarn] [yarn]	yarn install v1.22.5
[         script:yarn] [yarn]	[1/4] Resolving packages...
[         script:yarn] [yarn]	[2/4] Fetching packages...
> txaReportResources
[      script:monitor] [txAdmin] Sending resources list to txAdmin.
[         script:yarn] Error: [yarn]	error execa@7.2.0: The engine "node" is incompatible with this module. Expected version "4.18.0 || 6.14.0 || >=18.0.0". Got "16.9.1"
[         script:yarn] Error: [yarn]	error Found incompatible module.
[         script:yarn] [yarn]	info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[ citizen-server-impl] Building resource seatbelt failed.
[ citizen-server-impl] Error data: yarn failed!

**Comment by MrGriefs** [comment]
Disable the `yarn` resource. It is outdated, won't be updated and is riddle with bugs and compatibility issues.
If you have a resource which depends on the `yarn` resource, ask the author to update it or run the cli command `yarn install --production` inside that resource manually.

**Comment by MrGriefs** [comment]
Closing as wontfix as this issue is generated by a third-party resource.

**Comment by ZacerLivo** [comment]
what do we do?
