### ISSUE TITLE
Error in F8 and doesn't work

### ISSUE THREAD

**Issue by Simonfblarsen** [TFNRP/seatbelt#4]
Still getting errors after the last fix. [
![Screenshot_3](https://user-images.githubusercontent.com/94665249/142563347-8f0beff2-3e89-442f-bd7f-b09a4387d99b.png)
](url)

**Comment by MrGriefs** [comment]
Make sure to update the script by downloading the [latest release](https://github.com/TFNRP/seatbelt/releases/latest) and replacing it in your `resource` folder.

**Comment by Simonfblarsen** [comment]
I did. I replaced the whole script and still getting that error

**Comment by MrGriefs** [comment]
The error in the provided screenshot can only occur in releases prior the latest. Make sure you have restarted the script with `restart seatbelt` or `/restart seatbelt` using in-game chat.

**Comment by Simonfblarsen** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/94665249/142564561-e85e5a37-eeaa-4079-9f3e-24efedb7264f.png)
I replaced the whole script and restartet my server but it is still happening

**Comment by MrGriefs** [comment]
I cannot reproduce your issue. Please provide reproduction steps.

**Comment by RockySouthpaw** [comment]
> ![Screenshot_2](https://user-images.githubusercontent.com/94665249/142564561-e85e5a37-eeaa-4079-9f3e-24efedb7264f.png)
> I replaced the whole script and restartet my server but it is still happening

Your util file probably isn’t loading as this is where the function is located.

**Comment by Simonfblarsen** [comment]
![1](https://user-images.githubusercontent.com/94665249/142566668-699e4863-8c9d-42f7-815f-d077c1094289.png)
![Screenshot_4](https://user-images.githubusercontent.com/94665249/142566671-6a4d92a5-ea51-484c-add0-6068764706ea.png)
![Screenshot_5](https://user-images.githubusercontent.com/94665249/142566672-52ef1e20-8350-47d4-8f6d-a60e54a129ff.png)
![8](https://user-images.githubusercontent.com/94665249/142566724-58d6a73d-4cbd-49fb-8be0-553441f6839e.png)
![9](https://user-images.githubusercontent.com/94665249/142566726-300d0c41-95ba-4902-bddf-b18fd0b2a953.png)

**Comment by Simonfblarsen** [comment]
The resource is starting but its giving me these errors when i enter any vehicle

**Comment by MrGriefs** [comment]
What is your server build version?
