### ISSUE TITLE
Opening seatbelt while driving will throw you out of the car

### ISSUE THREAD

**Issue by ToasterF16** [TFNRP/seatbelt#5]
If you open the seatbelt while driving, it will launch you out of the car just as if you had an accident.

Tested on latest artifacts with onesync legacy.

**Comment by MrGriefs** [comment]
Were you driving at a consistent speed? If so, what was that speed?
If not, please detail the start and end velocity of the vehicle and the duration it took to reach the end velocity.

**Comment by ToasterF16** [comment]
> Were you driving at a consistent speed? If so, what was that speed? If not, please detail the start and end velocity of the vehicle and the duration it took to reach the end velocity.

https://gfycat.com/ImmenseFamiliarFreshwatereel

**Comment by MrGriefs** [comment]
That is expected behaviour when going from 80 MPH to 28 MPH within 2 seconds.
If this is not to your liking, you can increase or decrease the velocity threshold by change the integer `50`, representing MPH: https://github.com/TFNRP/seatbelt/blob/main/client.lua#L110

**Comment by MrGriefs** [comment]
If you need further help, feel free to reopen this issue.
