### ISSUE TITLE
Spotting players from a far distance that they are not wearing seatbelts.

### ISSUE THREAD

**Issue by Simonfblarsen** [TFNRP/seatbelt#6]
I'm not getting any errors but yesteday i spotted my friend not wearing a seatbelt when he was far away from me, and he spotted me too from far distance. Not sure if its because we are using bliptags, /duty.

**Comment by MrGriefs** [comment]
- What is your server build version?
- Which OneSync are you using?
- Can you estimate the distance?

**Comment by Simonfblarsen** [comment]
Server build 
![Screenshot_13](https://user-images.githubusercontent.com/94665249/142745874-e5cc2969-068f-43a9-9a00-2f9f3b0b362b.png)

Onesync is just set to onesync on

Can't estimate distance

**Comment by MrGriefs** [comment]
That's the game build, not your server build.

**Comment by Simonfblarsen** [comment]
![Screenshot_14](https://user-images.githubusercontent.com/94665249/142746187-f7bcc3b0-faa5-49e3-b400-b0b0e243036f.png)
