### ISSUE TITLE
Suggestion: vehicle category instead of LEO status

### ISSUE THREAD

**Issue by ToasterF16** [TFNRP/seatbelt#8]
Not an issue, more a suggestion: to make this script optionally framework independent, you could add an option to have the script check for vehicle type instead of framework LEO status and by doing 2 things:

1) only show LEO observations to front right and left seat of emergency vehicles and
2) exclude occupants of emergency vehicles from seatbelt observations in general

**Comment by MrGriefs** [comment]
The script already is standalone and does not require any dependencies, but offers optional out-of-the-box support for other frameworks if detected.
LEOs are not excluded from notifications to other LEOs and this will not be changed in the future, however, an optional configuration field may be added.
Please ensure everything you've stated in an issue is factually correct before submitting it.
